name: Keep Supabase alive

on:
  schedule:
    - cron: "0 12 */3 * *"
  workflow_dispatch:

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Supabase
        run: curl https://nnzyxcoijtesmaevzcha.supabase.co/rest/v1/
